{
	"nodes":[
		{"id":"2f8a6b1b1b510cfe","x":-1171,"y":-139,"width":671,"height":759,"type":"text","text":"\n### throws关键字\n在方法头（方法声明）中使用throws关键字，声明该方法内部可能抛出的一种或多种异常类型。\n\n### throw关键字\nthrow的对象必须是Throwable类型的。Error是Throwable类型，也可以使用throw抛出，也可以被捕获。\n在方法体（方法定义）中使用throw关键字，抛出一个异常对象。\n\nthrows和throw并没有强制要求一起使用；方法头使用throws声明了异常，方法体可以没有throw异常；方法体throw了异常，方法头也可以没有throws声明异常。\n\n但是要注意：throw抛出的受检查异常必须要被捕获或继续抛出\n\n如果一个方法的方法头没有声明throws异常，但是方法体里throw了异常，在try-catch块中调用该方法，也可以捕获到异常。\n\n调用一个方法头声明了可能抛出异常的方法时，必须处理这些可能产生的异常。处理的方法有两种：\n1. try-catch块，捕获处理异常\n2. 向外继续抛出异常\n\n\n\n\n"},
		{"id":"4ee36023af0185b5","x":-1171,"y":680,"width":971,"height":2560,"type":"text","text":"### 异常的分类\nJava中的异常都是Throwable类型的\n![[java异常类图.png]]\n> [!faq] 什么是受检异常？\n> 受编译器检查的异常，使用throw抛出的受检异常，必须在代码中处理。\n\n下面代码可以正常编译运行\n```java\npublic class Test {  \n    public static void main(String[] args)  {  \n        new Test().a();  \n    }  \n  \n    public void a() {  \n        throw new RuntimeException();  \n  \n    }  \n}\n\n```\n但是下面代码无法编译通过\n```java\npublic class Test {  \n    public static void main(String[] args)  {  \n        new Test().a();  \n    }  \n  \n    public void a() {  \n        throw new Exception();  \n  \n    }  \n}\n\n```\n因为Exception是受检异常，必须在代码中处理（捕获异常/继续抛出）\n1. 捕获异常\n```java\npublic class Test {  \n    public static void main(String[] args)  {  \n        new Test().a();  \n    }  \n  \n    public void a() {  \n        try {  \n            throw new Exception();  \n        } catch (Exception e) {  \n\t        // 如果catch中抛出了受检异常，还要继续处理\n            throw new RuntimeException(e);  \n        }  \n  \n    }  \n}\n```\n2. 继续向外层方法抛出异常\n```java\npublic class Test {  \n    public static void main(String[] args)  {  \n        new Test().a();  \n    }  \n  \n    public void a() throws Exception {  \n        throw new Exception();  \n  \n    }  \n}\n```\n\n\n非受检异常（运行时异常）\nRuntimeException及其子类\nError类型及其子类\n\n\n受检异常\nException和Exception子类中排除非受检异常\n编译时会检查，必须显示的捕获处理\n\n\n\n"},
		{"id":"dd8ac11d016ba247","type":"file","file":"resources/unsorted/Java异常与错误.md","x":-40,"y":120,"width":1228,"height":1000},
		{"id":"92a44b5f9fbd4a3e","x":-1961,"y":823,"width":641,"height":337,"type":"text","text":"出现异常后，代码是否会继续执行？\n1. 代码捕获处理了异常，后续代码可以运行\n2. 捕获了异常，处理异常时又出现了异常\n3. 出现了非受检异常\n\n"}
	],
	"edges":[]
}